# Generated by Django 5.2.5 on 2025-09-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='city',
        ),
        migrations.RemoveField(
            model_name='request',
            name='date_needed',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
